---
version: 2
jobs:
  build_test:
    docker:
      - image: circleci/python:latest
        environment:
          FLASK_APP: app.py
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t app .
      - run: pip3 install --user flask
      - run: FLASK_APP=app.py flask run -h 0.0.0.0 &
      - run: curl http://127.0.0.1:5000

workflows:
  version: 2
  build_deploy:
    jobs:
      - build_test:
          filters:
            tags:
              ignore: ""
